//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the StronglyTypedResourceBuilder tool (ResXFileCodeGenerator).
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. The class is generated as public so that XAML
//     can reference the strings with {x:Static res:Resources.Xxx}.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleRollCall.Properties
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleRollCall.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string Back
        {
            get { return ResourceManager.GetString("Back", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选项.
        /// </summary>
        public static string Options
        {
            get { return ResourceManager.GetString("Options", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关.
        /// </summary>
        public static string ToggleOff
        {
            get { return ResourceManager.GetString("ToggleOff", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 开.
        /// </summary>
        public static string ToggleOn
        {
            get { return ResourceManager.GetString("ToggleOn", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 清除.
        /// </summary>
        public static string ClearFile
        {
            get { return ResourceManager.GetString("ClearFile", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copyright 2026 SXZ11454. All rights reserved..
        /// </summary>
        public static string Copyright
        {
            get { return ResourceManager.GetString("Copyright", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择文件....
        /// </summary>
        public static string Browse
        {
            get { return ResourceManager.GetString("Browse", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string Confirm
        {
            get { return ResourceManager.GetString("Confirm", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 文本编码.
        /// </summary>
        public static string Encoding
        {
            get { return ResourceManager.GetString("Encoding", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 名单文件.
        /// </summary>
        public static string File
        {
            get { return ResourceManager.GetString("File", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string Language
        {
            get { return ResourceManager.GetString("Language", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 许可协议：MIT.
        /// </summary>
        public static string License
        {
            get { return ResourceManager.GetString("License", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动停止.
        /// </summary>
        public static string AutoStop
        {
            get { return ResourceManager.GetString("AutoStop", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 机器学习.
        /// </summary>
        public static string MachineLearning
        {
            get { return ResourceManager.GetString("MachineLearning", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 多账户.
        /// </summary>
        public static string MultiAccountTooltip
        {
            get { return ResourceManager.GetString("MultiAccountTooltip", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 名单为空，请先在设置中选择名单文件.
        /// </summary>
        public static string NoNames
        {
            get { return ResourceManager.GetString("NoNames", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Notice
        {
            get { return ResourceManager.GetString("Notice", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开文件.
        /// </summary>
        public static string OpenFileTooltip
        {
            get { return ResourceManager.GetString("OpenFileTooltip", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽取人数.
        /// </summary>
        public static string PeopleCount
        {
            get { return ResourceManager.GetString("PeopleCount", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 暂停.
        /// </summary>
        public static string PauseTooltip
        {
            get { return ResourceManager.GetString("PauseTooltip", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to GitHub 仓库.
        /// </summary>
        public static string Repository
        {
            get { return ResourceManager.GetString("Repository", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 开始.
        /// </summary>
        public static string StartTooltip
        {
            get { return ResourceManager.GetString("StartTooltip", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 重置.
        /// </summary>
        public static string ResetTooltip
        {
            get { return ResourceManager.GetString("ResetTooltip", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Settings
        {
            get { return ResourceManager.GetString("Settings", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string SettingsTooltip
        {
            get { return ResourceManager.GetString("SettingsTooltip", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 文本文件|*.txt|所有文件|*.*.
        /// </summary>
        public static string TextFileFilter
        {
            get { return ResourceManager.GetString("TextFileFilter", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        public static string Theme
        {
            get { return ResourceManager.GetString("Theme", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        public static string ThemeDark
        {
            get { return ResourceManager.GetString("ThemeDark", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        public static string ThemeLight
        {
            get { return ResourceManager.GetString("ThemeLight", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string ThemeSystem
        {
            get { return ResourceManager.GetString("ThemeSystem", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 版本 .
        /// </summary>
        public static string Version
        {
            get { return ResourceManager.GetString("Version", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 等待开抽.
        /// </summary>
        public static string Waiting
        {
            get { return ResourceManager.GetString("Waiting", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 点名器.
        /// </summary>
        public static string WindowTitle
        {
            get { return ResourceManager.GetString("WindowTitle", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 爆率.
        /// </summary>
        public static string Odds
        {
            get { return ResourceManager.GetString("Odds", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 人员.
        /// </summary>
        public static string OddsPerson
        {
            get { return ResourceManager.GetString("OddsPerson", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 爆率.
        /// </summary>
        public static string OddsWeight
        {
            get { return ResourceManager.GetString("OddsWeight", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 是否启用.
        /// </summary>
        public static string OddsEnabled
        {
            get { return ResourceManager.GetString("OddsEnabled", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0 = 永不抽中，50 = 正常抽取，100 = 必中；留空自动恢复为 50。.
        /// </summary>
        public static string OddsHint
        {
            get { return ResourceManager.GetString("OddsHint", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除此行.
        /// </summary>
        public static string DeleteRow
        {
            get { return ResourceManager.GetString("DeleteRow", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 新增一行.
        /// </summary>
        public static string AddRow
        {
            get { return ResourceManager.GetString("AddRow", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无人可抽：所有人的爆率都为 0。.
        /// </summary>
        public static string OddsNoOne
        {
            get { return ResourceManager.GetString("OddsNoOne", resourceCulture); }
        }
    }
}
